name: 'oms_dbt_proj'
version: '1.0.0'
config-version: 2

profile: 'oms_dbt_proj'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]


models:
  oms_dbt_proj:
    +transient: false
    stg:
      +schema: L2_PROCESSING
      +materialized: view  # Default for everything in stg
      
      # If you want specific files to be tables instead:
      orders_stg:
        +materialized: table
      orderitems_stg:
        +materialized: table
    customerrevenue:
      materialized: table
      schema: L3_CONSUMPTION
    orders_fact:
      schema: L2_PROCESSING
      materialized: table
    storeperformance:
      materialized: table
      schema: L3_CONSUMPTION