oms_dbt_proj:
  target: dev
  outputs:
    dev:
      type: snowflake
      role: DBT_TRANSFORMER_ROLE
      warehouse: COMPUTE_WH
      database: DEV_ANALYSE_DB
      schema: L3_CONSUMPTION
      threads: 8

    test:
      type: snowflake
      role: DBT_TRANSFORMER_ROLE
      warehouse: COMPUTE_WH
      database: TEST_ANALYSE_DB
      schema: L3_CONSUMPTION
      threads: 8

    prod:
      type: snowflake
      role: DBT_TRANSFORMER_ROLE
      warehouse: COMPUTE_WH
      database: PROD_ANALYSE_DB
      schema: L3_CONSUMPTION
      threads: 8